version: '3'

name: deephaven-traefik

services:
  foo:
    image: ghcr.io/deephaven/server:0.24.0
    labels:
      - 'traefik.http.routers.foo.tls=true'
      - 'traefik.http.routers.foo.rule=PathPrefix(`/foo/`) || HeaderRegexp(`Referer`, `https://localhost/foo/.*`)'
      - 'traefik.http.routers.foo.middlewares=foo_stripprefix'
      - 'traefik.http.middlewares.foo_stripprefix.stripprefix.prefixes=/foo,/foo/'
      - 'traefik.http.services.foo.loadbalancer.server.port=10000'
      - 'traefik.http.services.foo.loadbalancer.server.scheme=h2c'

  bar:
    image: ghcr.io/deephaven/server:0.24.0
    labels:
      - 'traefik.http.routers.bar.tls=true'
      - 'traefik.http.routers.bar.rule=PathPrefix(`/bar/`) || HeaderRegexp(`Referer`, `https://localhost/bar/.*`)'
      - 'traefik.http.routers.bar.middlewares=bar_stripprefix'
      - 'traefik.http.middlewares.bar_stripprefix.stripprefix.prefixes=/bar,/bar/'
      - 'traefik.http.services.bar.loadbalancer.server.port=10000'
      - 'traefik.http.services.bar.loadbalancer.server.scheme=h2c'

  baz:
    image: ghcr.io/deephaven/server:0.24.0
    labels:
      - 'traefik.http.routers.baz.tls=true'
      - 'traefik.http.routers.baz.rule=PathPrefix(`/baz/`) || HeaderRegexp(`Referer`, `https://localhost/baz/.*`)'
      - 'traefik.http.routers.baz.middlewares=baz_stripprefix'
      - 'traefik.http.middlewares.baz_stripprefix.stripprefix.prefixes=/baz,/baz/'
      - 'traefik.http.services.baz.loadbalancer.server.port=10000'
      - 'traefik.http.services.baz.loadbalancer.server.scheme=h2c'

  reverse-proxy:
    image: traefik:v3.0
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.constraints=Label(`io.deephaven.image.type`,`server`)'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web-secure.address=:443'
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
