version: '3'

name: deephaven-traefik

services:
  deephaven-foo:
    image: ghcr.io/deephaven/server:0.19.1
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.deephaven-foo.tls=true'
      - 'traefik.http.routers.deephaven-foo.rule=Host(`deephaven-foo.localhost`)'
      - 'traefik.http.services.deephaven-foo.loadbalancer.server.port=10000'
      - 'traefik.http.services.deephaven-foo.loadbalancer.server.scheme=h2c'

  deephaven-bar:
    image: ghcr.io/deephaven/server:0.19.1
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.deephaven-bar.tls=true'
      - 'traefik.http.routers.deephaven-bar.rule=Host(`deephaven-bar.localhost`)'
      - 'traefik.http.services.deephaven-bar.loadbalancer.server.port=10000'
      - 'traefik.http.services.deephaven-bar.loadbalancer.server.scheme=h2c'

  reverse-proxy:
    image: traefik:v2.9
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web-secure.address=:443'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
